// Copyright (c) 2018 Jerome Froelich
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/jeromefroe/heimdallr/pkg/apis/heimdallr/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HTTPCheckLister helps list HTTPChecks.
type HTTPCheckLister interface {
	// List lists all HTTPChecks in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.HTTPCheck, err error)
	// HTTPChecks returns an object that can list and get HTTPChecks.
	HTTPChecks(namespace string) HTTPCheckNamespaceLister
	HTTPCheckListerExpansion
}

// hTTPCheckLister implements the HTTPCheckLister interface.
type hTTPCheckLister struct {
	indexer cache.Indexer
}

// NewHTTPCheckLister returns a new HTTPCheckLister.
func NewHTTPCheckLister(indexer cache.Indexer) HTTPCheckLister {
	return &hTTPCheckLister{indexer: indexer}
}

// List lists all HTTPChecks in the indexer.
func (s *hTTPCheckLister) List(selector labels.Selector) (ret []*v1alpha1.HTTPCheck, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HTTPCheck))
	})
	return ret, err
}

// HTTPChecks returns an object that can list and get HTTPChecks.
func (s *hTTPCheckLister) HTTPChecks(namespace string) HTTPCheckNamespaceLister {
	return hTTPCheckNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// HTTPCheckNamespaceLister helps list and get HTTPChecks.
type HTTPCheckNamespaceLister interface {
	// List lists all HTTPChecks in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.HTTPCheck, err error)
	// Get retrieves the HTTPCheck from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.HTTPCheck, error)
	HTTPCheckNamespaceListerExpansion
}

// hTTPCheckNamespaceLister implements the HTTPCheckNamespaceLister
// interface.
type hTTPCheckNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all HTTPChecks in the indexer for a given namespace.
func (s hTTPCheckNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.HTTPCheck, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HTTPCheck))
	})
	return ret, err
}

// Get retrieves the HTTPCheck from the indexer for a given namespace and name.
func (s hTTPCheckNamespaceLister) Get(name string) (*v1alpha1.HTTPCheck, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("httpcheck"), name)
	}
	return obj.(*v1alpha1.HTTPCheck), nil
}
