// Copyright (c) 2018 Jerome Froelich
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/jeromefroe/heimdallr/pkg/apis/heimdallr/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHTTPChecks implements HTTPCheckInterface
type FakeHTTPChecks struct {
	Fake *FakeHeimdallrV1alpha1
	ns   string
}

var httpchecksResource = schema.GroupVersionResource{Group: "heimdallr.froe.io", Version: "v1alpha1", Resource: "httpchecks"}

var httpchecksKind = schema.GroupVersionKind{Group: "heimdallr.froe.io", Version: "v1alpha1", Kind: "HTTPCheck"}

// Get takes name of the hTTPCheck, and returns the corresponding hTTPCheck object, and an error if there is any.
func (c *FakeHTTPChecks) Get(name string, options v1.GetOptions) (result *v1alpha1.HTTPCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(httpchecksResource, c.ns, name), &v1alpha1.HTTPCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HTTPCheck), err
}

// List takes label and field selectors, and returns the list of HTTPChecks that match those selectors.
func (c *FakeHTTPChecks) List(opts v1.ListOptions) (result *v1alpha1.HTTPCheckList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(httpchecksResource, httpchecksKind, c.ns, opts), &v1alpha1.HTTPCheckList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HTTPCheckList{ListMeta: obj.(*v1alpha1.HTTPCheckList).ListMeta}
	for _, item := range obj.(*v1alpha1.HTTPCheckList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hTTPChecks.
func (c *FakeHTTPChecks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(httpchecksResource, c.ns, opts))

}

// Create takes the representation of a hTTPCheck and creates it.  Returns the server's representation of the hTTPCheck, and an error, if there is any.
func (c *FakeHTTPChecks) Create(hTTPCheck *v1alpha1.HTTPCheck) (result *v1alpha1.HTTPCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(httpchecksResource, c.ns, hTTPCheck), &v1alpha1.HTTPCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HTTPCheck), err
}

// Update takes the representation of a hTTPCheck and updates it. Returns the server's representation of the hTTPCheck, and an error, if there is any.
func (c *FakeHTTPChecks) Update(hTTPCheck *v1alpha1.HTTPCheck) (result *v1alpha1.HTTPCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(httpchecksResource, c.ns, hTTPCheck), &v1alpha1.HTTPCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HTTPCheck), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHTTPChecks) UpdateStatus(hTTPCheck *v1alpha1.HTTPCheck) (*v1alpha1.HTTPCheck, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(httpchecksResource, "status", c.ns, hTTPCheck), &v1alpha1.HTTPCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HTTPCheck), err
}

// Delete takes name of the hTTPCheck and deletes it. Returns an error if one occurs.
func (c *FakeHTTPChecks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(httpchecksResource, c.ns, name), &v1alpha1.HTTPCheck{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHTTPChecks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(httpchecksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.HTTPCheckList{})
	return err
}

// Patch applies the patch and returns the patched hTTPCheck.
func (c *FakeHTTPChecks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HTTPCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(httpchecksResource, c.ns, name, data, subresources...), &v1alpha1.HTTPCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HTTPCheck), err
}
